# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Mpp::Methods::Tempo::Account::Eth::Key; end
module Mpp::Methods::Tempo::Attribution::Eth::Util; end
module Mpp::Methods::Tempo::ChargeIntent::RLP; end
module Mpp::Methods::Tempo::FeePayer::RLP; end
module Mpp::Methods::Tempo::TempoMethod::Pytempo::Call; end
module Mpp::Methods::Tempo::TempoMethod::Pytempo::TempoTransaction; end
